# DON'T MODIFY
# generated by
# rails runner lib/seed_generator.rb > db/seeds.rb
user = User.find_by({:email=>"sarah@gmail.com"})
user = User.create!({:email=>"sarah@gmail.com", :password=>"password", :password_confirmation=>"password"}) if user.nil?
user.update!({})
user = nil
user = User.find_by({:email=>"bob@gmail.com"})
user = User.create!({:email=>"bob@gmail.com", :password=>"azerty", :password_confirmation=>"azerty"}) if user.nil?
user.update!({})
user = nil
user = User.find_by({:email=>"yan@gmail.com"})
user = User.create!({:email=>"yan@gmail.com", :password=>"password", :password_confirmation=>"password"}) if user.nil?
user.update!({})
user = nil
tag = ActsAsTaggableOn::Tag.find_by(name: "bookkeeping")
ActsAsTaggableOn::Tag.create!(name: "bookkeeping") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "user experience")
ActsAsTaggableOn::Tag.create!(name: "user experience") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "developer tools")
ActsAsTaggableOn::Tag.create!(name: "developer tools") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "marketing")
ActsAsTaggableOn::Tag.create!(name: "marketing") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "CRM")
ActsAsTaggableOn::Tag.create!(name: "CRM") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "design tools")
ActsAsTaggableOn::Tag.create!(name: "design tools") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "productivity")
ActsAsTaggableOn::Tag.create!(name: "productivity") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "analytics")
ActsAsTaggableOn::Tag.create!(name: "analytics") if tag.nil?
