# DON'T MODIFY
# generated by
# rails runner lib/seed_generator.rb > db/seeds.rb
user = User.find_by({:email=>"sarah@gmail.com"})
user = User.create!({:email=>"sarah@gmail.com", :password=>"password", :password_confirmation=>"password"}) if user.nil?
user.update!({})
user = nil
user = User.find_by({:email=>"bob@gmail.com"})
user = User.create!({:email=>"bob@gmail.com", :password=>"azerty", :password_confirmation=>"azerty"}) if user.nil?
user.update!({})
user = nil
user = User.find_by({:email=>"yan@gmail.com"})
user = User.create!({:email=>"yan@gmail.com", :password=>"password", :password_confirmation=>"password"}) if user.nil?
user.update!({})
user = nil
tag = ActsAsTaggableOn::Tag.find_by(name: "bookkeeping")
ActsAsTaggableOn::Tag.create!(name: "bookkeeping") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "user experience")
ActsAsTaggableOn::Tag.create!(name: "user experience") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "developer tools")
ActsAsTaggableOn::Tag.create!(name: "developer tools") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "marketing")
ActsAsTaggableOn::Tag.create!(name: "marketing") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "CRM")
ActsAsTaggableOn::Tag.create!(name: "CRM") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "design tools")
ActsAsTaggableOn::Tag.create!(name: "design tools") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "productivity")
ActsAsTaggableOn::Tag.create!(name: "productivity") if tag.nil?
tag = ActsAsTaggableOn::Tag.find_by(name: "analytics")
ActsAsTaggableOn::Tag.create!(name: "analytics") if tag.nil?
product = Product.find_by({:name=>"Pilot", :url=>"https://pilot.com/"})
product = Product.create!({:name=>"Pilot", :url=>"https://pilot.com/"}) if product.nil?
product.update!({:bio=>"Bookkeeping for startups, powered by humans and software", :info=>"Pilot is a bookkeeping company that focuses on startups—with a twist. Their bookkeepers are assisted by software that automates the most error-prone pieces, so the books are always incredibly accurate. Kind of like having a cyborg army working for you, only way less scary.", :image_url=>"https://ph-files.imgix.net/a1ec86fb-de76-4add-95ec-814a8d19f6e2.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Bench Accounting", :url=>"https://bench.co/"})
product = Product.create!({:name=>"Bench Accounting", :url=>"https://bench.co/"}) if product.nil?
product.update!({:bio=>"Bookkeeping done for you", :info=>"Bench does your small business books for you. We'll connect you with one of our in-house bookkeepers. Then, they'll prepare your monthly and year-end financials—so you don't have to.Sign up for a trial, and get 1 month of bookkeeping done risk-free.", :image_url=>"https://ph-files.imgix.net/c2167080-c0c4-4f86-ab87-d1133440b45a.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"SimpleKeep", :url=>"http://simplekeep.co"})
product = Product.create!({:name=>"SimpleKeep", :url=>"http://simplekeep.co"}) if product.nil?
product.update!({:bio=>"Simple book keeping, payroll, & invoicing for businesses.", :info=>nil, :image_url=>"https://ph-files.imgix.net/1f2ed450-1793-41e7-b35e-ea3e24c05744.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Crypto Tax Prep by Happy Tax", :url=>"https://cryptotaxprep.com/product-hunt"})
product = Product.create!({:name=>"Crypto Tax Prep by Happy Tax", :url=>"https://cryptotaxprep.com/product-hunt"}) if product.nil?
product.update!({:bio=>"Cryptocurrency tax prep, accounting + bookkeeping", :info=>"Crypto Tax Prep by Happy Tax are cryptocurrency CPAs who provide tax preparation and accounting for the crypto space. IRS guidelines require all crypto transactions to be reported. Users include miners, day traders, casual investors, early adopters, and businesses accepting bitcoin as a payment method. $100 off Crypto Tax Prep for Product Hunters.", :image_url=>"https://ph-files.imgix.net/25fb564a-ae42-412b-908e-5e295fca25d9.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Botkeeper", :url=>"http://botkehttps//play.google.com/store/apps/details?id=com.botkeeper.clienthub&hl=en_USeper.com&ref=producthunt"})
product = Product.create!({:name=>"Botkeeper", :url=>"http://botkehttps//play.google.com/store/apps/details?id=com.botkeeper.clienthub&hl=en_USeper.com&ref=producthunt"}) if product.nil?
product.update!({:bio=>"Virtual bookkeeping powered by AI & Senior Accountants", :info=>"Better than humans, better than machines. Automated bookkeeping with a human touch. Benefit from the most accurate accounting, 24/7, real-time dashboards and reporting, all while saving on average 30-50% compared to a traditional bookkeeper or outsourced firm.", :image_url=>"https://ph-files.imgix.net/557d0d36-5600-4d11-b033-92ee332e6210.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Bookleaf", :url=>"https://bookleaf.co"})
product = Product.create!({:name=>"Bookleaf", :url=>"https://bookleaf.co"}) if product.nil?
product.update!({:bio=>"Bookkeeping for indie hackers & small businesses", :info=>"Bookleaf takes care of bookkeeping for busy indie hackers, founders, and small business owners. Bookkeeping is done by licensed accountants from world-class firms like PwC and EY.Prices start as low as $99/mo.", :image_url=>"https://ph-files.imgix.net/39d2978f-f6e9-45fb-b182-23dedce87dc1.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Contalink", :url=>"https://www.contalink.com/"})
product = Product.create!({:name=>"Contalink", :url=>"https://www.contalink.com/"}) if product.nil?
product.update!({:bio=>"Bookkeeping automation for accountants in Mexico", :info=>"Contalink is a SAAS accounting platform to help accounting firms in Mexico automate their work plus collaborate and serve their customers better online.", :image_url=>"https://ph-files.imgix.net/daad1978-0064-4f76-96e8-3f628c7071fb.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Receipt Stash", :url=>"http://www.receipt-stash.com"})
product = Product.create!({:name=>"Receipt Stash", :url=>"http://www.receipt-stash.com"}) if product.nil?
product.update!({:bio=>"Automated bookkeeping for accounts payable", :info=>"Receipt Stash simplifies accounts payable bookkeeping by automatically extracting expense information from any receipt or invoice, and categorising items using dynamic supplier rules. All expense items are stored securely in a single, easily searchable cloud based account and can be published to your accounting software with the push of a button.", :image_url=>"https://ph-files.imgix.net/79b4432c-4d33-4fe9-afb5-29ab4c4c2822.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Simply123", :url=>"https://www.simply123books.com/"})
product = Product.create!({:name=>"Simply123", :url=>"https://www.simply123books.com/"}) if product.nil?
product.update!({:bio=>"BookKeeping made easy in 3 simple steps", :info=>"Simply123\n BookKeeping made easy in 3 simple steps\nStep 1 : Select a Category (Income/Expense)\nStep 2 : Enter Details\nStep 3 : Submit\nIt is that easy. Simply one, two, three...TRY IT FREE!", :image_url=>"https://ph-files.imgix.net/b524c5d1-9b28-40a7-a4a6-22030b7c6dfa.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Asto", :url=>"https://asto.io/"})
product = Product.create!({:name=>"Asto", :url=>"https://asto.io/"}) if product.nil?
product.update!({:bio=>"Simplify your bookkeeping and keep your cashflow positive", :info=>"The app to simplify bookkeeping and make your cashflow positive. Invoices. Expenses. Balances and more.Save time on repetitive admin. Create invoices on-the-go. Keep tabs on your bank accounts.", :image_url=>"https://ph-files.imgix.net/9e1dd01b-d282-4b88-a8f6-4b8e93e6b9c9.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("bookkeeping", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"UX Lifecycle - The business guide to implementing great software user experiences", :url=>"http://uxlifecycle.com"})
product = Product.create!({:name=>"UX Lifecycle - The business guide to implementing great software user experiences", :url=>"http://uxlifecycle.com"}) if product.nil?
product.update!({:bio=>"This book is for organisations starting their UX journey ", :info=>nil, :image_url=>"https://ph-files.imgix.net/5d45fd20-ec49-46e6-abfc-a20dd55ff58a.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Fluxguard - End User Experience Monitoring", :url=>"https://fluxguard.com"})
product = Product.create!({:name=>"Fluxguard - End User Experience Monitoring", :url=>"https://fluxguard.com"}) if product.nil?
product.update!({:bio=>"Exploratory testing & change monitoring of your site", :info=>"- Still doing manual \"sanity checks?\"- Are site visitors your (unpaid) QA testers? 😱Fluxguard automates UI/UX QA. We'll crawl your site. We'll alert you to every pixel & DOM change. Monitor form submissions, clicks, and more. Catch breaking changes to key flows (login, order) before your users. 😁", :image_url=>"https://ph-files.imgix.net/39df0506-e877-43ab-b89a-24a6c10e89ca.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"User Experiences That Matter (Second Edition)", :url=>"https://www.userexperiencesmatter.com/"})
product = Product.create!({:name=>"User Experiences That Matter (Second Edition)", :url=>"https://www.userexperiencesmatter.com/"}) if product.nil?
product.update!({:bio=>"What defines a great user experience?", :info=>"User Experiences that Matter gives you an introduction to creating great user experiences by focusing on the human being using the product. Let’s get you on the path on creating happy, loyal customers!", :image_url=>"https://ph-files.imgix.net/abffbb80-66d8-4a7c-b2f8-e64a3469c25f.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"User Experiences That Matter", :url=>"https://www.userexperiencesmatter.com/"})
product = Product.create!({:name=>"User Experiences That Matter", :url=>"https://www.userexperiencesmatter.com/"}) if product.nil?
product.update!({:bio=>"Take your product from liked by you, to loved by your users!", :info=>nil, :image_url=>"https://ph-files.imgix.net/abffbb80-66d8-4a7c-b2f8-e64a3469c25f.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Lean UX: Applying Lean Principles to Improve User Experience", :url=>"http://amzn.to/1U0ryiP&tag=prodhunt04-20"})
product = Product.create!({:name=>"Lean UX: Applying Lean Principles to Improve User Experience", :url=>"http://amzn.to/1U0ryiP&tag=prodhunt04-20"}) if product.nil?
product.update!({:bio=>"Applying Lean Principles to Improve User Experience", :info=>nil, :image_url=>"https://ph-files.imgix.net/7d375fe3-073b-4c8d-9803-164ba2dc4536.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Sketching User Experiences: Getting the Design Right and the Right Design", :url=>"https://www.amazon.co.uk/dp/0123740371&tag=prodhunt04-20"})
product = Product.create!({:name=>"Sketching User Experiences: Getting the Design Right and the Right Design", :url=>"https://www.amazon.co.uk/dp/0123740371&tag=prodhunt04-20"}) if product.nil?
product.update!({:bio=>"Sketching and early prototyping design methods", :info=>nil, :image_url=>"https://ph-files.imgix.net/eedcb0bc-c0cd-4ef8-a682-0cd014d22791.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"LUXD: Learn User Experience Design", :url=>"https://web-crunch.com/books/luxd/"})
product = Product.create!({:name=>"LUXD: Learn User Experience Design", :url=>"https://web-crunch.com/books/luxd/"}) if product.nil?
product.update!({:bio=>"An eBook for aspiring UX designers", :info=>nil, :image_url=>"https://ph-files.imgix.net/6906c8a4-30ce-472c-ae0f-49948578abe7.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"The User Experience Team of One", :url=>"http://rosenfeldmedia.com/books/the-user-experience-team-of-one/"})
product = Product.create!({:name=>"The User Experience Team of One", :url=>"http://rosenfeldmedia.com/books/the-user-experience-team-of-one/"}) if product.nil?
product.update!({:bio=>"A Research and Design Survival Guide", :info=>nil, :image_url=>"https://ph-files.imgix.net/2d2c3839-7f70-4416-82ad-36a247556e7d.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"The Elements of User Experience", :url=>"http://www.amazon.com/o/ASIN/0735712026/ref=nosim/jjgnet-20/"})
product = Product.create!({:name=>"The Elements of User Experience", :url=>"http://www.amazon.com/o/ASIN/0735712026/ref=nosim/jjgnet-20/"}) if product.nil?
product.update!({:bio=>"User-centered design for the web", :info=>nil, :image_url=>"https://ph-files.imgix.net/24ce3ccc-7062-4652-8418-34fa3be1c272.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Evolt Design Suite", :url=>"https://evolt.io/en/"})
product = Product.create!({:name=>"Evolt Design Suite", :url=>"https://evolt.io/en/"}) if product.nil?
product.update!({:bio=>"The design thinking suite to create great user experiences", :info=>"Tools, tutorials, design and innovation experts, all in one place! The most intuitive platform to design innovation (Persona, Storyboard...and more to come)", :image_url=>"https://ph-files.imgix.net/e3bc7bd1-fd5f-4e27-9592-6cdfc591fb18.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("user experience", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Profitable developer tools database", :url=>"https://gumroad.com/l/profitable-developer-tools"})
product = Product.create!({:name=>"Profitable developer tools database", :url=>"https://gumroad.com/l/profitable-developer-tools"}) if product.nil?
product.update!({:bio=>"A database of 103+ hand-curated profitable developer tools", :info=>"- A live database of 103+ hand-curated profitable developer tools.- An insights report about these profitable developer tools.", :image_url=>"https://ph-files.imgix.net/1200ce71-f611-4bdd-b96b-07e9f964289c.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"GitHub Student Developer Pack", :url=>"https://education.github.com/pack"})
product = Product.create!({:name=>"GitHub Student Developer Pack", :url=>"https://education.github.com/pack"}) if product.nil?
product.update!({:bio=>"The best developer tools, free for students.", :info=>nil, :image_url=>"https://ph-files.imgix.net/84745bf8-4783-4ba3-9785-d241165f6b00.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"LaunchKit - Open Source", :url=>"https://github.com/launchkit/launchkit"})
product = Product.create!({:name=>"LaunchKit - Open Source", :url=>"https://github.com/launchkit/launchkit"}) if product.nil?
product.update!({:bio=>"A popular suite of developer tools, now 100% open source.", :info=>nil, :image_url=>"https://ph-files.imgix.net/06669635-7522-4165-a7fb-96bfba0846b8.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Pretty Awesome Lists", :url=>"https://www.prettyawesomelists.com"})
product = Product.create!({:name=>"Pretty Awesome Lists", :url=>"https://www.prettyawesomelists.com"}) if product.nil?
product.update!({:bio=>"Over 25,000 developer tools in one place 🔥", :info=>"Pretty Awesome Lists crawls available awesome lists (e.g. programming, work, games, etc.) , collects interesting information about each link, takes a screenshot and then makes them pretty for you to explore.", :image_url=>"https://ph-files.imgix.net/3244f241-8cab-456d-8384-cc328d5be4f8.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Weights & Biases", :url=>"https://www.wandb.com/"})
product = Product.create!({:name=>"Weights & Biases", :url=>"https://www.wandb.com/"}) if product.nil?
product.update!({:bio=>"Developer tools for deep learning & machine learning", :info=>"Easily track & save the performance of your deep learning models. In < 5 lines of code, integrate Keras, Tensorflow, Pytorch, or Fastai models so that every hyperparameter & metric is saved each time code runs. https://www.youtube.com/watch?v=icy3XkZ5jBk", :image_url=>"https://ph-files.imgix.net/170e24f0-0b12-45d1-b25b-a2c4bc2f6e4d.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"SmallDevTools", :url=>"https://smalldev.tools/"})
product = Product.create!({:name=>"SmallDevTools", :url=>"https://smalldev.tools/"}) if product.nil?
product.update!({:bio=>"Handy developer tools with a delightful interface", :info=>"Smalldev.tools provide 20+ tools that helps developers with commonly performed tasks like Encoding/Decoding, Minifying, Test Dummy data set and a lot more.", :image_url=>"https://ph-files.imgix.net/1cb7041a-e35b-4878-a8d4-669cecf1dde3.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Bugout", :url=>"https://bugout.dev"})
product = Product.create!({:name=>"Bugout", :url=>"https://bugout.dev"}) if product.nil?
product.update!({:bio=>"Mixpanel for developer tools", :info=>"Bugout lets creators of APIs, libraries, and CLIs understand:⠀- Who their users are- How they use their software- What issues they face⠀All while respecting users' privacy.⠀If a user is having an issue, Bugout directs them to fixes in real time.", :image_url=>"https://ph-files.imgix.net/47f095a1-924b-452a-8aae-298c680cae1b.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"whatdevsneed", :url=>"https://whatdevsneed.com"})
product = Product.create!({:name=>"whatdevsneed", :url=>"https://whatdevsneed.com"}) if product.nil?
product.update!({:bio=>"Discover new developer tools, no ads, no tracking", :info=>"This is whatdevsneed. A curated list of developer tools, without annoying ads, cookies, tracking, popups, or signups. Just developer tools.", :image_url=>"https://ph-files.imgix.net/7d09768f-152e-480e-a1f2-cbff9f79f68a.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Serverless-Dev-Tools", :url=>"https://github.com/Theodo-UK/sls-dev-tools"})
product = Product.create!({:name=>"Serverless-Dev-Tools", :url=>"https://github.com/Theodo-UK/sls-dev-tools"}) if product.nil?
product.update!({:bio=>"Developer tools for the serverless world", :info=>"sls-dev-tools improves the Developer-Experience (DX) of building state-of-the-art Serverless applications.This open-source tool enables you to make intelligent decisions while developing and debugging, directly in your terminal.", :image_url=>"https://ph-files.imgix.net/12f4f4b5-9a5e-4046-8ab3-fefbf723c131.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"ValueTools", :url=>"https://valuetools.co/"})
product = Product.create!({:name=>"ValueTools", :url=>"https://valuetools.co/"}) if product.nil?
product.update!({:bio=>"All important developer tools in one app", :info=>"🧰 ValueTools is a collection of important tools frequently used by developers, all bundled together in a sleek windows application. Forget about finding sites where you paste your sensitive information just to do some basic work.", :image_url=>"https://ph-files.imgix.net/8134d5a3-95d8-4dff-9765-0812181266d4.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("developer tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Marketing Stack", :url=>"http://marketingstack.io/"})
product = Product.create!({:name=>"Marketing Stack", :url=>"http://marketingstack.io/"}) if product.nil?
product.update!({:bio=>"A curated directory of marketing resources & tools", :info=>"", :image_url=>"https://ph-files.imgix.net/bf987837-651e-43de-979d-2c7b14a40932.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Marketing Resources List", :url=>"https://usefyi.com/templates/marketing-templates"})
product = Product.create!({:name=>"Marketing Resources List", :url=>"https://usefyi.com/templates/marketing-templates"}) if product.nil?
product.update!({:bio=>"The biggest collection of free marketing resources", :info=>"An up-to-date list of 308+ free marketing templates and resources across 16 categories of Marketing from popular document apps including G Suite, Airtable, Coda, Notion, Trello, Tettra, Miro and more. This is the largest collection of marketing resources!", :image_url=>"https://ph-files.imgix.net/bf2f50b6-cf92-4e2b-90dd-887c3f2e1ca2.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Content Marketing Stack", :url=>"http://www.contentmarketingstack.co/"})
product = Product.create!({:name=>"Content Marketing Stack", :url=>"http://www.contentmarketingstack.co/"}) if product.nil?
product.update!({:bio=>"A curated directory of content marketing resources", :info=>"Content Marketing Stack is a curated directory of content marketing resources & tutorials.", :image_url=>"https://ph-files.imgix.net/26c37180-c3af-4a18-9035-c203b62618b0.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Marketing Examples", :url=>"https://marketingexamples.com"})
product = Product.create!({:name=>"Marketing Examples", :url=>"https://marketingexamples.com"}) if product.nil?
product.update!({:bio=>"A gallery of real world marketing examples", :info=>"Real world marketing examples from successful companies.🤔Want to perfect your cold email, boost referrals or improve SEO? 💡Browse the case studies or filter by category. 😊See something you like. And get inspired.It's like Dribbble, but for marketers. ", :image_url=>"https://ph-files.imgix.net/a6c9b9fd-15da-41c2-935e-ce47c11a33da.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"The Influencer Marketing Stack", :url=>"https://mention.com/en/influencer-marketing/"})
product = Product.create!({:name=>"The Influencer Marketing Stack", :url=>"https://mention.com/en/influencer-marketing/"}) if product.nil?
product.update!({:bio=>"Free resources to launch a killer campaign", :info=>"We’ve teamed up with 5 incredible influencer marketing brands to create a spectacular FREE resource hub. You’ll find everything you need to know to launch a killer influencer campaign right away!Thanks to Buzzstream, Bitly, The Shelf, Later, and Shane Barker for your wisdom and resources.", :image_url=>"https://ph-files.imgix.net/6e0e195a-6b25-4480-bca1-f2b70c9bd30d.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Zero to Marketing", :url=>"https://www.zerotomarketing.com"})
product = Product.create!({:name=>"Zero to Marketing", :url=>"https://www.zerotomarketing.com"}) if product.nil?
product.update!({:bio=>"Short case studies that help you get better at marketing", :info=>"Every two weeks I pick a website and write a short case study explaining exactly how I’d grow it", :image_url=>"https://ph-files.imgix.net/67537b96-2ee0-44fc-bc96-3902da866459.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"App Marketing Stack", :url=>"http://appmarketingstack.com"})
product = Product.create!({:name=>"App Marketing Stack", :url=>"http://appmarketingstack.com"}) if product.nil?
product.update!({:bio=>"200+ handpicked resources on app marketing and mobile growth", :info=>nil, :image_url=>"https://ph-files.imgix.net/cfd00600-2d56-4303-a0e4-0eac66e82681.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Intercom on Marketing", :url=>"https://www.intercom.com/books/marketing"})
product = Product.create!({:name=>"Intercom on Marketing", :url=>"https://www.intercom.com/books/marketing"}) if product.nil?
product.update!({:bio=>"The marketing book for startups", :info=>"Intercom on Marketing is packed with ideas, suggestions and lessons from across the entire spectrum of marketing, from messaging to monetization, that we learned over the last 6 years, as we grew from 0 to over 20,000 customers.", :image_url=>"https://ph-files.imgix.net/c9fd25b1-0db3-4410-ab9d-5283011020d3.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Marketing for Developers 2.0", :url=>"https://devmarketing.xyz/ph/"})
product = Product.create!({:name=>"Marketing for Developers 2.0", :url=>"https://devmarketing.xyz/ph/"}) if product.nil?
product.update!({:bio=>"A book for programmers who want to learn marketing", :info=>"Marketing for Developers is a book that helps programmers build, launch, and get their first 100 customers. Tired of making apps that no one wants? Join 5,000+ readers and learn the basics of marketing software products.", :image_url=>"https://ph-files.imgix.net/e8e3c330-7cd7-4ffe-abf4-19fab8444b64.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Marketing for Startups", :url=>"https://welovenocode.com/marketingforstartups"})
product = Product.create!({:name=>"Marketing for Startups", :url=>"https://welovenocode.com/marketingforstartups"}) if product.nil?
product.update!({:bio=>"Free e-book with 47 practical user acquisition tactics", :info=>"47 practical tactics to get customers and achieve hockey stick growth. Lessons that helped startups grow from zero to over $100,000 MRR.", :image_url=>"https://ph-files.imgix.net/c96ba751-39ac-4a60-a5dd-8df3c6816593.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("marketing", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Salesflare CRM", :url=>"https://salesflare.com"})
product = Product.create!({:name=>"Salesflare CRM", :url=>"https://salesflare.com"}) if product.nil?
product.update!({:bio=>"Simple yet powerful CRM for small businesses selling B2B", :info=>"The easiest to use sales CRM for small businesses. Salesflare automates your data to build better relationships and make more sales. A fast, visual and easy-to-use sales machine. Built on happiness with the latest tech, by humans for humans.", :image_url=>"https://ph-files.imgix.net/ddb3d205-b7ce-4072-a914-18f9ae59c52f.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Onesheet CRM", :url=>"http://www.onesheetcrm.com/"})
product = Product.create!({:name=>"Onesheet CRM", :url=>"http://www.onesheetcrm.com/"}) if product.nil?
product.update!({:bio=>"The Simple CRM for Google Sheets", :info=>nil, :image_url=>"https://ph-files.imgix.net/75be7f86-1183-430f-8548-5261dae44870.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"FollowUp Personal CRM", :url=>"https://followup.cc/followup-personal-crm"})
product = Product.create!({:name=>"FollowUp Personal CRM", :url=>"https://followup.cc/followup-personal-crm"}) if product.nil?
product.update!({:bio=>"The personal CRM for Gmail", :info=>"FollowUp is a personal CRM that makes managing your professional relationships easy. Set followups, write notes, schedule reminders, create events, and more without ever leaving your inbox.", :image_url=>"https://ph-files.imgix.net/aaca2e36-3370-4c0e-acbb-9e6bb7f86c4e.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Freshsales CRM", :url=>"https://www.freshsales.io/?utm_source=producthunt&utm_medium=referral&utm_campaign=producthuntlaunch&ref=producthunt"})
product = Product.create!({:name=>"Freshsales CRM", :url=>"https://www.freshsales.io/?utm_source=producthunt&utm_medium=referral&utm_campaign=producthuntlaunch&ref=producthunt"}) if product.nil?
product.update!({:bio=>"A full-fledged CRM for high-velocity sales teams.", :info=>"With Freshsales CRM, your team can now use AI-based lead scoring, built-in phone, email, activity capture and more.", :image_url=>"https://ph-files.imgix.net/47379563-022b-419d-bcba-7330335e4c33.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"InStream CRM", :url=>"http://instream.io"})
product = Product.create!({:name=>"InStream CRM", :url=>"http://instream.io"}) if product.nil?
product.update!({:bio=>"Business relationship management platform - CRM alternative", :info=>nil, :image_url=>"https://ph-files.imgix.net/668f108b-f7ef-48c4-b361-d67c48d2a872.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Sortd Sales CRM for Gmail", :url=>"https://sortd.com/sales"})
product = Product.create!({:name=>"Sortd Sales CRM for Gmail", :url=>"https://sortd.com/sales"}) if product.nil?
product.update!({:bio=>"Uncomplicated, effortless, Trello-style CRM in your Gmail", :info=>"An uncomplicated, easy to use CRM for professionals & teams using Gmail/G-Suite. You’re working your leads & dealing with customers in email anyway - manage it all visually, with practically no additional effort.A Trello-style sales pipeline, follow-up reminders & sales reports right in Gmail help you see your opportunities clearly & close more.", :image_url=>"https://ph-files.imgix.net/b66cd47d-94f1-400e-b328-7af0f598e607.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"PipeDrive CRM", :url=>"http://www.pipedrive.com"})
product = Product.create!({:name=>"PipeDrive CRM", :url=>"http://www.pipedrive.com"}) if product.nil?
product.update!({:bio=>"Effortless pipeline management.", :info=>nil, :image_url=>"https://ph-files.imgix.net/edbe8a51-ea7a-48f9-929d-19d4c233f0bc.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Overloop CRM", :url=>"https://overloop.com"})
product = Product.create!({:name=>"Overloop CRM", :url=>"https://overloop.com"}) if product.nil?
product.update!({:bio=>"Free CRM made for conversations", :info=>"Everything starts with a good conversation. That’s why our CRM is designed to help you start more conversations and close more deals.Main features:- Outbound sales- Deals & Pipelines- Web Forms- Workflows & automation- Email Finder- Forecasting- ...🎁 75% off for 3 monthsLogin to get promo code", :image_url=>"https://ph-files.imgix.net/3ff29b69-da1c-40e7-a280-d71ad5f12764.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"HubSpot CRM", :url=>"http://www.hubspot.com/products/crm"})
product = Product.create!({:name=>"HubSpot CRM", :url=>"http://www.hubspot.com/products/crm"}) if product.nil?
product.update!({:bio=>"Organize, track, and sell", :info=>nil, :image_url=>"https://ph-files.imgix.net/40ae8b1a-ca3a-4e9e-96a2-51f7c4b80ef8.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"NetHunt CRM", :url=>"https://nethunt.com/"})
product = Product.create!({:name=>"NetHunt CRM", :url=>"https://nethunt.com/"}) if product.nil?
product.update!({:bio=>"Turn Gmail into a smart CRM", :info=>"NetHunt CRM is service to turn your Gmail inbox into a full-featured CRM system.It helps you organize your business processes into the easy-to-manage and analyze Records available from Gmail. This allows you to manage and supervise sales, clients, project, support cases and other business activities within the familiar Google Apps ecosystem.", :image_url=>"https://ph-files.imgix.net/1389e318-2035-4a64-8292-1c5b0819d88b.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("CRM", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"2015 Design Tools", :url=>"http://tools.subtraction.com"})
product = Product.create!({:name=>"2015 Design Tools", :url=>"http://tools.subtraction.com"}) if product.nil?
product.update!({:bio=>"Results from survey of 4,000+ designers on their fave tools.", :info=>nil, :image_url=>"https://ph-files.imgix.net/73fa0960-32e9-49f4-8952-a96efd87d705.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Design Tools Weekly", :url=>"https://flawlessapp.io/designtoolsweekly"})
product = Product.create!({:name=>"Design Tools Weekly", :url=>"https://flawlessapp.io/designtoolsweekly"}) if product.nil?
product.update!({:bio=>"Design tools & guides on using them, sent to your 📨", :info=>"Thanks for checking out Design Tools Weekly!What it’s about:— series of interesting design tools and practical guides— delivered to your inbox weekly, absolutely free— 300+ tools grouped into categories— learn at your own speed, constantly", :image_url=>"https://ph-files.imgix.net/85574ca4-c813-407f-bd68-43d11e7e11af.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"2021 Design Tools Survey", :url=>"https://uxtools.co/survey-2021/"})
product = Product.create!({:name=>"2021 Design Tools Survey", :url=>"https://uxtools.co/survey-2021/"}) if product.nil?
product.update!({:bio=>"See the industry's trends and find new tools", :info=>"📣📊 The 2021 Design Tools Survey results are live!🧠 We've been crunching numbers for the past month and we're ready to share this year's results!👀 Find new and exciting tools for your team, see industry trends, and share the knowledge!", :image_url=>"https://ph-files.imgix.net/5f4bb8d9-3213-42c1-a55d-5e7acadd0f07.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Undesign", :url=>"https://undesign.learn.uno"})
product = Product.create!({:name=>"Undesign", :url=>"https://undesign.learn.uno"}) if product.nil?
product.update!({:bio=>"Free design tools and resources for your projects", :info=>"Collection of free design tools and resources for makers, developers and designers", :image_url=>"https://ph-files.imgix.net/a3d3bd50-0d01-4215-94c6-a12701178084.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Avocode 3.0", :url=>"https://avocode.com/release-3-0"})
product = Product.create!({:name=>"Avocode 3.0", :url=>"https://avocode.com/release-3-0"}) if product.nil?
product.update!({:bio=>"Open, hand-off, & inspect designs files without design tools", :info=>"Avocode 3 is the first cross-platform design hand-off tool for design collaboration, version control, and inspecting of Sketch, XD, Photoshop, and Figma design files, on Windows, Linux, or macOS. Independent on design tools, with unlimited storage, unlimited versions and unlimited projects.", :image_url=>"https://ph-files.imgix.net/2a0f2cd8-00dd-4807-87de-dfee4f685665.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"DesignValley", :url=>"https://www.designvalley.club"})
product = Product.create!({:name=>"DesignValley", :url=>"https://www.designvalley.club"}) if product.nil?
product.update!({:bio=>"Discover, vote and share your favorite design tools 🥇", :info=>"🥇DesignValley is a curated depository for designers/design enthusiasts that exhibits the hottest design tools/resources.You're able to discover, vote and share your favourite design resources. ", :image_url=>"https://ph-files.imgix.net/2d078e11-8a0a-485f-b7c7-0bc6791be333.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Craft Stock, from InVision", :url=>"https://www.invisionapp.com/craft#stock"})
product = Product.create!({:name=>"Craft Stock, from InVision", :url=>"https://www.invisionapp.com/craft#stock"}) if product.nil?
product.update!({:bio=>"The best design tools meet the best imagery", :info=>nil, :image_url=>"https://ph-files.imgix.net/99f37d14-fe19-43dd-9693-0e0f8dcce425.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Public Design Vault", :url=>"https://publicdesignvault.com/"})
product = Product.create!({:name=>"Public Design Vault", :url=>"https://publicdesignvault.com/"}) if product.nil?
product.update!({:bio=>"500+ design tools for public good, all in one place", :info=>"Public Design Vault is Startup Stash meets design meets government. It's a curated directory of 500+ design tools & resources for public good, all in one place. Super useful for folks working at the intersection of human-centered design, innovation and public/social impact. ", :image_url=>"https://ph-files.imgix.net/625e0791-2e84-4abb-8e37-d84df6e808e4.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Apply Pixels", :url=>"https://applypixels.com/"})
product = Product.create!({:name=>"Apply Pixels", :url=>"https://applypixels.com/"}) if product.nil?
product.update!({:bio=>"Downloadable evolving Industry Standard Design Tools", :info=>nil, :image_url=>"https://ph-files.imgix.net/58e0c26a-373f-4ba7-8cd5-62cabf522c0b.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"UX Tools", :url=>"http://uxtools.co/"})
product = Product.create!({:name=>"UX Tools", :url=>"http://uxtools.co/"}) if product.nil?
product.update!({:bio=>"Compare UX design tools side-by-side", :info=>"UX Tools is the easiest way to alleviate your tools anxiety by comparing the industry's best UX tools side by side. When was the last time you heard someone ask, \"Which is best: InVision, Framer, or Marvel?\" Send them a link to uxtools.co and let them decide for themselves.", :image_url=>"https://ph-files.imgix.net/3f19db2e-b0ac-454b-8b82-b9fdd26a5cfa.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("design tools", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Productivity Tools by Dropbox", :url=>"https://www.dropbox.com/productivity"})
product = Product.create!({:name=>"Productivity Tools by Dropbox", :url=>"https://www.dropbox.com/productivity"}) if product.nil?
product.update!({:bio=>"Scan, share, collaborate & provide feedback on your ideas", :info=>nil, :image_url=>"https://ph-files.imgix.net/496fb7b6-a5a0-4fe0-b018-36fc365eb651.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Productivity.so", :url=>"https://productivity.so"})
product = Product.create!({:name=>"Productivity.so", :url=>"https://productivity.so"}) if product.nil?
product.update!({:bio=>"Shortcuts and hacks for your favorite tools", :info=>"A curated library of productivity hacks. Uncover the hidden 1% in every tool you use. This will compound and be your new superpowers.", :image_url=>"https://ph-files.imgix.net/149ca86b-ff3e-4b4b-a21b-92bb4eff6db7.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"The Ultimate Productivity Stack", :url=>"http://theproductivitystack.com/"})
product = Product.create!({:name=>"The Ultimate Productivity Stack", :url=>"http://theproductivitystack.com/"}) if product.nil?
product.update!({:bio=>"Curated directory of tools to supercharge your productivity", :info=>" The Ultimate Productivity Stack is a curated directory of resources and tools to help you boost your productivity.", :image_url=>"https://ph-files.imgix.net/b2e07fc9-c076-471e-bbdf-c87e0d329be2.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Productivity Planner", :url=>"https://www.kickstarter.com/projects/intelligentchange/productivity-planner-get-more-done-and-beat-procra"})
product = Product.create!({:name=>"Productivity Planner", :url=>"https://www.kickstarter.com/projects/intelligentchange/productivity-planner-get-more-done-and-beat-procra"}) if product.nil?
product.update!({:bio=>"Get more done and beat procrastination", :info=>"", :image_url=>"https://ph-files.imgix.net/3f7731bb-6d61-48dc-b988-afbc1675c329.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"ProductivityMentor", :url=>"https://www.mentorist.app/productivitymentor/"})
product = Product.create!({:name=>"ProductivityMentor", :url=>"https://www.mentorist.app/productivitymentor/"}) if product.nil?
product.update!({:bio=>"500 skills from the best books to boost your productivity", :info=>"The problem: Self-help books are great but it's hard to convert the knowledge into action.The solution: ProductivityMentor offers 500 concrete action-steps inspired by books from the world's best authors to boost your productivity in a fun gamified way.", :image_url=>"https://ph-files.imgix.net/11522a39-0675-4d2f-ad39-04afe475229d.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Command Line Productivity", :url=>"http://commandlineproductivity.com"})
product = Product.create!({:name=>"Command Line Productivity", :url=>"http://commandlineproductivity.com"}) if product.nil?
product.update!({:bio=>"A Pomodoro meets GTD productivity pack for Alfred", :info=>"Command Line Productivity is a productivity workflow system built on Alfred for Mac. It turns your Mac back into a place where work gets done instead of another distraction device. ", :image_url=>"https://ph-files.imgix.net/11930efa-bd57-4c11-8ff7-91859179d187.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"VS Code Extensions for Productivity", :url=>"https://saviomartin.gumroad.com/l/vscode-extentions"})
product = Product.create!({:name=>"VS Code Extensions for Productivity", :url=>"https://saviomartin.gumroad.com/l/vscode-extentions"}) if product.nil?
product.update!({:bio=>"Curated collection of 34 VS Code extensions for productivity", :info=>"I have evaluated over 250+ VS Code extensions and created a collection of 34 top VS Code extensions to supercharge your productivity 🔥. You'll find it very useful.Grab it now for $1, Don't miss it 🥳", :image_url=>"https://ph-files.imgix.net/fffad596-f704-4a2d-812e-5750cdfd1ff7.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"ipsm.io - Productivity Tools", :url=>"https://ipsm.io/"})
product = Product.create!({:name=>"ipsm.io - Productivity Tools", :url=>"https://ipsm.io/"}) if product.nil?
product.update!({:bio=>"Collection of productivity tools for developers & designers", :info=>"The project aims to provide tools to use during the development process. Generate Lorem Ipsum placeholder texts, custom color dummy images, and videos of different sizes. Use generated content to test the layout until the real content arrives. Give it a try!", :image_url=>"https://ph-files.imgix.net/a65fa8e8-54c5-4a1d-b4fa-175cc90727d5.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"YouTube Productivity Mode", :url=>"https://chrome.google.com/webstore/detail/youtube-productivity-mode/hfmieanpcjmhneggofkdjhmlabjmbbaj"})
product = Product.create!({:name=>"YouTube Productivity Mode", :url=>"https://chrome.google.com/webstore/detail/youtube-productivity-mode/hfmieanpcjmhneggofkdjhmlabjmbbaj"}) if product.nil?
product.update!({:bio=>"Reduce distractions on YouTube and gain back your focus", :info=>"Switch YPM in “Productivity Mode” to blur all the thumbnails on YouTube so that the catchy and clickbaity thumbnails don’t grab your attention. So now if you get redirected to YouTube while working/studying, the recommended thumbnails won’t catch your eyes.", :image_url=>"https://ph-files.imgix.net/dfa6913a-0bcf-4650-be76-9afcd82541c0.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Productivity Notebook", :url=>"http://productivitynotebook.felixoginni.com"})
product = Product.create!({:name=>"Productivity Notebook", :url=>"http://productivitynotebook.felixoginni.com"}) if product.nil?
product.update!({:bio=>"Maintain your focus & stay motivated all day. Everyday.", :info=>nil, :image_url=>"https://ph-files.imgix.net/07dc6435-cf0b-4cc2-8c28-4553eed3e640.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("productivity", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Narrative BI for Google Analytics", :url=>"https://www.narrative.bi/ga-narratives"})
product = Product.create!({:name=>"Narrative BI for Google Analytics", :url=>"https://www.narrative.bi/ga-narratives"}) if product.nil?
product.update!({:bio=>"Automated Insights from your Google Analytics", :info=>"Narrative BI is automated no-code analytics for your Google Analytics data.🙊 Personalized reports in natural language😻 Automated anomaly detection😇 Slack integration🏁 Fast and easy to onboard🥳 No expertise required", :image_url=>"https://ph-files.imgix.net/4ddceb91-d927-44f9-87b5-e288a9a177b8.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Fathom Analytics", :url=>"https://usefathom.com"})
product = Product.create!({:name=>"Fathom Analytics", :url=>"https://usefathom.com"}) if product.nil?
product.update!({:bio=>"Simple, trustworthy website analytics (finally)", :info=>"Fathom Analytics is a simpler and more privacy-focused alternative to Google Analytics.Fathom respects the privacy of your users and does not collect any personally identifiable information. All while giving you the information you need about your site, so you can make smarter decisions about your design and content.", :image_url=>"https://ph-files.imgix.net/1b62fea7-e785-4704-a82e-283d2ef1693e.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Nacho Analytics", :url=>"https://www.nachoanalytics.com"})
product = Product.create!({:name=>"Nacho Analytics", :url=>"https://www.nachoanalytics.com"}) if product.nil?
product.update!({:bio=>"View any company's analytics", :info=>"See anyone's Analytics account.  View their sales, and how they get them, all in real-time.  See which growth hacks work, and which flop.  See which products and features get used and which ones don't.  ", :image_url=>"https://ph-files.imgix.net/be47022e-4a43-4a1c-9703-dc07cb1b2ab9.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Plausible Analytics", :url=>"https://plausible.io/"})
product = Product.create!({:name=>"Plausible Analytics", :url=>"https://plausible.io/"}) if product.nil?
product.update!({:bio=>"Open source, privacy friendly Google Analytics alternative", :info=>"Plausible Analytics is a simple, open source, lightweight (< 1 KB) and privacy-friendly alternative to Google Analytics. Our mission is to reduce corporate surveillance by providing a web analytics tool which doesn’t come from the AdTech world.", :image_url=>"https://ph-files.imgix.net/84db18d0-6f62-4d19-8afa-968ee4bc6751.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Simple Analytics", :url=>"https://simpleanalytics.io"})
product = Product.create!({:name=>"Simple Analytics", :url=>"https://simpleanalytics.io"}) if product.nil?
product.update!({:bio=>"Simple, clean, and privacy-friendly analytics 📊", :info=>"Simple Analytics gives you the analytics you need without invading the privacy of your users, with a clean interface, and simple integration.", :image_url=>"https://ph-files.imgix.net/a8526e4b-08dd-448b-834d-8e2861329608.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Indicative Analytics", :url=>"https://www.indicative.com/"})
product = Product.create!({:name=>"Indicative Analytics", :url=>"https://www.indicative.com/"}) if product.nil?
product.update!({:bio=>"Customer analytics for everyone. No code or SQL required.", :info=>"Indicative is a Customer Analytics platform designed for non-technical users. Powerful self-service analytics enable Product Managers, Marketers, and Data Analysts to make informed decisions by understanding the complete customer journey.", :image_url=>"https://ph-files.imgix.net/56f162c0-37f2-4a33-a05a-6a413f483bfe.jpeg?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Kuku Analytics", :url=>"https://kuku.io/en/analytics/"})
product = Product.create!({:name=>"Kuku Analytics", :url=>"https://kuku.io/en/analytics/"}) if product.nil?
product.update!({:bio=>"Smart social media analytics", :info=>nil, :image_url=>"https://ph-files.imgix.net/c60e1f84-593b-43ec-862f-89670e1279f5.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Influencer Analytics by Interceptd", :url=>"https://interceptd.com/influencer-analytics/"})
product = Product.create!({:name=>"Influencer Analytics by Interceptd", :url=>"https://interceptd.com/influencer-analytics/"}) if product.nil?
product.update!({:bio=>"Gain control of your influencer campaigns", :info=>"Influencer Analytics by Interceptd enables you to analyze influencer audience, engagement, URLs, posts and reach in-depth before, during and after an Instagram influencer campaign.", :image_url=>"https://ph-files.imgix.net/a648aef8-ae5a-4b27-a86e-27023c64cc82.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Native Analytics by Keen IO", :url=>"https://keen.io/native-analytics/"})
product = Product.create!({:name=>"Native Analytics by Keen IO", :url=>"https://keen.io/native-analytics/"}) if product.nil?
product.update!({:bio=>"Build and ship analytics features for your users.", :info=>nil, :image_url=>"https://ph-files.imgix.net/25e706bc-5b14-4c5c-88b2-f18ecb7acd9a.png?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
product = Product.find_by({:name=>"Intutel - Social Media Analytics", :url=>"https://intutel.com/products/social"})
product = Product.create!({:name=>"Intutel - Social Media Analytics", :url=>"https://intutel.com/products/social"}) if product.nil?
product.update!({:bio=>"Monitor brands & grow your social media with smart analytics", :info=>nil, :image_url=>"https://ph-files.imgix.net/6589d877-5951-48c5-baff-58b9e85eee50.gif?auto=format&auto=compress&codec=mozjpeg&cs=strip&w=160&h=160&fit=crop&dpr=3%203x%22"})
product.category_list.add("analytics", parse: true)
product.save!
product = nil
